version: "3"
services:
       login-app:
           container_name: userorder
           image: userorder
           restart: always
           build: .
           ports:
             - "2000:2000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'